---
- name: Set redis cluster port facts
  ansible.builtin.set_fact:
    redis_ports: "{{ redis_cluster_ports[(ansible_play_batch.index(inventory_hostname) * 2):(ansible_play_batch.index(inventory_hostname) * 2 + 2)] }}"
  when: redis_cluster_enabled == "yes"

- name: Create redis group
  ansible.builtin.group:
    name: redis
    state: present

- name: Create redis user
  ansible.builtin.user:
    name: redis
    group: redis
    shell: /sbin/nologin
    create_home: false

- name: Create redis data directories
  ansible.builtin.file:
    path: "{{ redis_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: '0755'
  loop: "{{ redis_ports }}"
  loop_control:
    loop_var: redis_port

- name: Deploy redis configuration
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_config }}"
    owner: redis
    group: redis
    mode: '0644'
    backup: true
  loop: "{{ redis_ports }}"
  loop_control:
    loop_var: redis_port
  notify: restart redis

- name: Deploy redis systemd service files
  ansible.builtin.template:
    src: redis.service.j2
    dest: "/etc/systemd/system/redis-{{ redis_port }}.service"
    owner: root
    group: root
    mode: '0644'
    backup: true
  loop: "{{ redis_ports }}"
  loop_control:
    loop_var: redis_port
  notify: restart redis

- name: Set redis directory permissions
  ansible.builtin.file:
    path: "{{ redis_root_path }}"
    owner: redis
    group: redis
    state: directory
    recurse: true
