---
- name: Check if redis is installed
  ansible.builtin.stat:
    path: "{{ redis_root_path }}"
  register: redis_installed

- name: Install redis
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: redis
  when: not redis_installed.stat.exists

- name: Configure redis
  ansible.builtin.import_tasks: configure.yml

- name: Initialize redis cluster
  ansible.builtin.import_tasks: cluster.yml
  when: redis_cluster_enabled == "yes"
