---
# vars file for rocketmq
# Internal/computed variables - do not override

# Computed from defaults
rocketmq_dir_name: "rocketmq-all-{{ rocketmq_version }}-bin-release"
rocketmq_pkg_name: "rocketmq-all-{{ rocketmq_version }}-bin-release.zip"

# Computed from inventory
host_ip: "{{ ansible_default_ipv4['address'] }}"
master_broker_name: "broker-m{{ ansible_play_batch.index(inventory_hostname) }}"
slave_broker_name: "broker-s{{ ansible_play_batch.index(inventory_hostname) }}"
namesrv_addr: "{% for index in range(ansible_play_batch|length) %}{{ ansible_play_batch[index] }}:{{ namesrv_port }}{% if not loop.last %};{% endif %}{% endfor %}"
bind_addr: "{{ host_ip }}"

# Service config paths
master_config: "{{ rocketmq_root_path }}/conf/2m-2s-sync/broker-m.properties"
slave_config: "{{ rocketmq_root_path }}/conf/2m-2s-sync/broker-s.properties"
