---
- name: Set kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    ignoreerrors: true
  loop: "{{ sysctl_params }}"

- name: Enable BBR congestion control
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    ignoreerrors: true
  loop: "{{ sysctl_bbr_params }}"
  when: sysctl_bbr_enabled
