---
# tasks file for fact

- name: Create custom facts directory
  ansible.builtin.file:
    path: "{{ fact_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy custom fact file
  ansible.builtin.template:
    src: forbidden.fact.j2
    dest: "{{ fact_dir }}/{{ fact_filename }}"
    owner: root
    group: root
    mode: '0644'

- name: Reload ansible facts
  ansible.builtin.setup:
    filter: ansible_local
