---
- name: restart rocketmq
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon_reload: true
    state: restarted
    enabled: true
  loop:
    - rocketmq-namesrv
    - rocketmq-master
    - rocketmq-slave

- name: Verify rocketmq is listening
  ansible.builtin.wait_for:
    host: "{{ host_ip }}"
    port: "{{ item }}"
    delay: 15
    timeout: 60
    state: started
  loop:
    - "{{ namesrv_port }}"
    - "{{ master_port }}"
    - "{{ slave_port }}"
  listen: restart rocketmq
