---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    state: restarted
    enabled: true

- name: Verify nginx is listening
  ansible.builtin.wait_for:
    host: "{{ host_ip }}"
    port: "{{ nginx_port }}"
    delay: 15
    timeout: 60
    state: started
  listen: restart nginx
