---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ _hostname }}"

- name: Map hostname in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address | regex_escape }}\s'
    line: "{{ _hostname_hosts_line }}"
    state: present
