---
- name: Create kafka group
  ansible.builtin.group:
    name: kafka
    state: present

- name: Create kafka user
  ansible.builtin.user:
    name: kafka
    group: kafka
    shell: /sbin/nologin
    create_home: true

- name: Generate cluster UUID
  ansible.builtin.command: bin/kafka-storage.sh random-uuid
  args:
    chdir: "{{ kafka_root_path }}"
  register: kafka_cluster_uuid
  when: kafka_cluster_uuid is not defined
  run_once: true

- name: Deploy kafka configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: kafka
    group: kafka
    mode: '0644'
    backup: true
  loop:
    - { src: server.properties.j2, dest: "{{ kafka_config }}" }
    - { src: kafka.service.j2, dest: /etc/systemd/system/kafka.service }
  notify: restart kafka

- name: Set kafka directory permissions
  ansible.builtin.file:
    path: "{{ kafka_root_path }}"
    owner: kafka
    group: kafka
    state: directory
    recurse: true
