---
- name: Check if kafka is installed
  ansible.builtin.stat:
    path: "{{ kafka_root_path }}"
  register: kafka_installed

- name: Install kafka
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: kafka
  when: not kafka_installed.stat.exists

- name: Configure kafka
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags: kafka
