---
- name: restart kafka
  ansible.builtin.systemd:
    name: kafka
    daemon_reload: true
    state: restarted
    enabled: true

- name: Verify kafka is listening
  ansible.builtin.wait_for:
    host: "{{ host_ip }}"
    port: 9092
    delay: 15
    timeout: 60
    state: started
  listen: restart kafka
