default_include: master.d/*.conf
gather_job_timeout: 10  # salt job
timeout: 5  # salt command and api
#show_jid: False
worker_threads: 10
auto_accept: False
publisher_acl:
  saltstack:
    - test.ping
    - state.sls
    - state.apply
    - state.highstate
    - grains.items
    - pillar.items
    - cmd.run
    - service.restart
    - service.status
    - pkg.install
    - pkg.upgrade
fileserver_backend:
  - roots
  - gitfs
file_roots:
  base:
    - /srv/salt/base
  dev:
    - /srv/salt/dev
  prod:
    - /srv/salt/prod
hash_type: sha256
#gitfs_remotes:
#  - git://github.com/saltstack/salt-states.git
pillar_roots:
  base:
    - /srv/salt/pillar
log_file: /var/log/salt/master
key_logfile: /var/log/salt/key
log_level: warning
log_level_logfile: info

# Security hardening
open_mode: False
drop_messages: True
