---
- name: restart docker
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart docker-cleanup timer
  ansible.builtin.systemd:
    name: docker-cleanup.timer
    daemon_reload: true
    state: restarted
    enabled: true
