# AWS steady-state inventory.
[aws]
# 10.1.1.0/24
# 10.1.2.0/24
# 10.10.1.0/24
# 10.11.2.0/24
52.77.168.160

# Add service topology groups as needed, then aggregate them under [aws:children].
# [kafka_cluster_aws]
# 10.1.0.[11:13]
#
# [aws:children]
# kafka_cluster_aws
