# GCP steady-state inventory.
[gcp]
34.140.227.70

# Add service topology groups as needed, then aggregate them under [gcp:children].
# [kafka_cluster_gcp]
# 10.2.0.[11:13]
#
# [gcp:children]
# kafka_cluster_gcp
