[kafka_east]
10.10.1.[1:3]

[nginx_east]
10.10.2.1

[redis_east]
# standalone
10.10.3.1
# cluster
10.10.3.[11:13]

[rocketmq_east]
# standalone
10.10.4.1
# 2m-2s-sync
10.10.4.[11:12]
# failover
10.10.4.[21:23]

[east:children]
kafka_east
nginx_east
redis_east
rocketmq_east

[west:children]
kafka_west
nginx_west
redis_west
rocketmq_west
