[kafka_kvm]
10.0.0.[1:3]

[nginx_kvm]
10.0.0.10

[redis_kvm]
# standalone
10.0.1.1
# cluster
10.0.1.[11:13]

[rocketmq_kvm]
# standalone
10.0.2.1
# 2m-2s-sync
10.0.2.[11:12]
# failover
10.0.2.[21:23]
