---
# Usage:
# standalone (single broker, replication factor = 1)
#   uv run ansible-playbook playbooks/kafka.yml --limit kafka_standalone_kvm
# 3-node cluster (KRaft quorum, replication factor = 3)
#   uv run ansible-playbook playbooks/kafka.yml --limit kafka_cluster_kvm -e "kafka_cluster_enabled=yes"

- name: Deploy Kafka
  hosts: all
  become: true
  serial: 1
  roles:
    - kafka
