---
# Usage:
#   ansible-playbook -i inventories/init.ini playbooks/kafka.yml --limit kvm
#   ansible-playbook -i inventories/init.ini playbooks/kafka.yml --limit cloud_aws
#   ansible-playbook -i inventories/init.ini playbooks/kafka.yml --limit cloud_gcp

- hosts: all
  remote_user: root
  become: true
  become_method: su
  gather_facts: false
  serial: 1
  roles:
    - kafka
