---
# Usage:
#   ansible-playbook -i inventories/init.ini playbooks/nginx.yml --limit nginx_standalone_kvm

- hosts: all
  remote_user: root
  become: yes
  become_method: su
  roles:
    - { role: nginx }
