---
# Usage:
#   ansible-playbook -i inventories/init.ini playbooks/nginx.yml --limit kvm
#   ansible-playbook -i inventories/init.ini playbooks/nginx.yml --limit cloud_aws
#   ansible-playbook -i inventories/init.ini playbooks/nginx.yml --limit cloud_gcp

- hosts: all
  remote_user: root
  become: yes
  become_method: su
  roles:
    - { role: nginx }
