---
# Usage:
# standalone
#   ansible-playbook playbooks/redis.yml --limit redis_east
# cluster
#   ansible-playbook playbooks/redis.yml --limit redis_east -e "redis_cluster_enabled=yes"

- hosts: redis
  remote_user: root
  become: true
  become_method: su
  gather_facts: false
  serial: 1
  roles:
    - redis
