---
# Usage:
# standalone
#   ansible-playbook -i inventories/init.ini playbooks/redis.yml --limit kvm
#   ansible-playbook -i inventories/init.ini playbooks/redis.yml --limit cloud_aws
#   ansible-playbook -i inventories/init.ini playbooks/redis.yml --limit cloud_gcp
# cluster
#   ansible-playbook -i inventories/init.ini playbooks/redis.yml --limit kvm -e "redis_cluster_enabled=yes"

- hosts: all
  remote_user: root
  become: true
  become_method: su
  gather_facts: false
  serial: 1
  roles:
    - redis
