---
# Usage:
# standalone mode
#   ansible-playbook playbooks/rocketmq.yml --limit rocketmq_east
# 2m-2s-sync mode
#   ansible-playbook playbooks/rocketmq.yml --limit rocketmq_east
# failover mode
#   ansible-playbook playbooks/rocketmq.yml --limit rocketmq_east

- hosts: all
  remote_user: root
  become: true
  become_method: su
  gather_facts: false
  serial: 1
  roles:
    - rocketmq
