---
- name: Check if categraf is installed
  ansible.builtin.stat:
    path: "{{ categraf_root_path }}"
  register: categraf_root_path_result

- name: Install categraf
  ansible.builtin.include_tasks: install.yml
  when: not categraf_root_path_result.stat.exists

- name: Configure categraf
  ansible.builtin.include_tasks: configure.yml
