---
- name: Check if rocketmq is installed
  ansible.builtin.stat:
    path: "{{ rocketmq_root_path }}"
  register: rocketmq_installed

- name: Install rocketmq
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: rocketmq
  when: not rocketmq_installed.stat.exists

- name: Configure rocketmq
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags: rocketmq
