---
- name: Check if nginx is installed
  ansible.builtin.stat:
    path: "{{ nginx_root_path }}"
  register: nginx_installed

- name: Install nginx
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: nginx
  when: not nginx_installed.stat.exists

- name: Configure nginx
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags: nginx
