# global variable
ansible_user: ansible
ansible_port: 300
# Use ansible-vault to encrypt: ansible-vault encrypt_string 'your_password' --name 'ansible_ssh_pass' --vault-id pwd.vault
ansible_ssh_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  REPLACE_WITH_VAULT_ENCRYPTED_VALUE
ansible_ssh_private_key_file: /opt/ansible/keys/all.key
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  REPLACE_WITH_VAULT_ENCRYPTED_VALUE
hostname_prefix: PROD
