# Vultr steady-state connection and privilege escalation.
ansible_user: devops
ansible_port: 22
ansible_ssh_private_key_file: keys/devops_key
ansible_become_method: sudo
ansible_become_user: root

ntp_timezone: UTC
ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
