---
- name: Configure resource limits
  ansible.builtin.include_tasks: limits.yml

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml
  when: security_firewall_enabled

- name: Configure password policy
  ansible.builtin.include_tasks: password.yml

- name: Harden filesystem
  ansible.builtin.include_tasks: filesystem.yml

- name: Disable unused services
  ansible.builtin.include_tasks: services.yml
