---
- name: Set password maximum age
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS   {{ security_password_max_days }}"
    state: present

- name: Set password minimum age
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS   {{ security_password_min_days }}"
    state: present

- name: Set password minimum length
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_LEN'
    line: "PASS_MIN_LEN    {{ security_password_min_len }}"
    state: present

- name: Set password warning age
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE   {{ security_password_warn_age }}"
    state: present
