---
- name: restart redis
  ansible.builtin.systemd:
    name: "redis-{{ redis_port }}"
    daemon_reload: true
    state: restarted
    enabled: true

- name: Verify redis is listening
  ansible.builtin.wait_for:
    host: "{{ host_ip }}"
    port: "{{ redis_port }}"
    delay: 15
    timeout: 60
    state: started
  listen: restart redis

- name: init redis cluster
  ansible.builtin.command: ./bin/redis-cli --cluster create {{ redis_cluster_init_info }} --cluster-replicas 1 --cluster-yes -a {{ redis_password }}
  args:
    chdir: "{{ redis_root_path }}"
  register: init_cluster_result

- name: Print cluster initialization result
  ansible.builtin.debug:
    msg: "{{ init_cluster_result.stdout }}"
  listen: init redis cluster
